<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tone Analysis Visualization</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
        }
        .container {
            width: 500px;
            margin: auto;
        }
        svg {
            border: 1px solid #ccc;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Tone Analysis from XML Data</h1>
        <p>This bar chart visualizes the occurrence of different tones found in the XML dataset.</p>
        
        <!-- Embed the SVG here generated by your XQuery -->
        <div id="chart">
            {
                let $tones := (
                    for $doc in collection("../xml/?select=*.xml")
                    return $doc//title/@tone/string()
                )
                let $tone-counts := map:merge(
                    for $tone in distinct-values($tones)
                    return map:entry($tone, count($tones[. eq $tone]))
                )
                let $max-count := max((map:keys($tone-counts) ! $tone-counts(.), 0))
                
                let $svg := 
                    <svg xmlns="http://www.w3.org/2000/svg" width="400" height="300">
                        <!-- Y-axis labels and grid lines -->
                        <g transform="translate(50,10)">
                            { 
                                for $y in 0 to 10
                                let $y-pos := 250 - ($y * 20)
                                return (
                                    <text x="-10" y="{$y-pos}" text-anchor="end" font-size="10">{ $y }</text>,
                                    <line x1="0" y1="{$y-pos}" x2="350" y2="{$y-pos}" stroke="lightgrey" stroke-width="1" />
                                )
                            }
                            
                            <!-- X-axis labels -->
                            { 
                                for $tone at $index in distinct-values($tones)
                                let $x-pos := ($index - 1) * 40 + 20
                                return <text x="{$x-pos}" y="270" text-anchor="middle" font-size="10">{ $tone }</text>
                            }
                            
                            <!-- Bars -->
                            { 
                                for $tone at $index in distinct-values($tones)
                                let $count := map:get($tone-counts, $tone)
                                let $x-pos := ($index - 1) * 40 + 10
                                let $bar-height := ($count * 20)
                                return <rect x="{$x-pos}" y="{250 - $bar-height}" width="20" height="{$bar-height}" fill="steelblue" />
                            }
                        </g>
                    </svg>
                return $svg
            }
        </div>
        
        <p>Each bar represents the number of times a specific tone appears in the dataset.</p>
    </div>
</body>
</html>